# Generated by Django 3.0.14 on 2022-04-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(db_column='dept_Name', max_length=32, primary_key=True, serialize=False)),
                ('building', models.CharField(blank=True, max_length=32, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('course_id', models.CharField(db_column='course_ID', max_length=6, primary_key=True, serialize=False)),
                ('sec_id', models.CharField(db_column='sec_ID', max_length=6)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('building', models.CharField(blank=True, max_length=32, null=True)),
                ('room', models.CharField(blank=True, max_length=32, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('total_credits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.ForeignKey(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usertype.Student')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'takes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('course', models.ForeignKey(db_column='course_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='teaches_section_course', serialize=False, to='usertype.Section')),
            ],
            options={
                'db_table': 'teaches',
                'managed': False,
            },
        ),
    ]
